# Generated by Django 6.0.3 on 2026-03-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_comment_updated_at_remove_reply_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('friends', 'Friends Only'), ('public', 'Public')], default='public', max_length=20),
        ),
    ]
