# Generated by Django 6.0.3 on 2026-03-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_public',
        ),
    ]
