# Generated by Django 6.0.3 on 2026-03-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
