# Generated by Django 6.0.3 on 2026-03-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
