# Generated by Django 6.0.3 on 2026-03-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagenotification',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
