# Generated by Django 6.0.3 on 2026-03-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_messagenotification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
