# Generated by Django 6.0.3 on 2026-03-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagenotification',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
